spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbancario
    username: root
    password: root
#    url: jdbc:mysql://localhost:3306/sbancario
#    username: root
#    password: root
    sql-script-encoding: UTF-8
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${JWT_SECRET:senhaPadrao}